site_name: UnitCommitment.jl
theme: cinder
copyright: "Copyright © 2020, UChicago Argonne, LLC. All Rights Reserved."
repo_url: https://github.com/ANL-CEEESA/unitcommitment.jl
edit_uri: edit/dev/src/docs/
nav:
    - Home: index.md
    - Usage: usage.md
    - Format: format.md
plugins:
  - search
markdown_extensions:
  - admonition  
  - mdx_math  
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - js/mathjax.js
docs_dir: src/docs
site_dir: docs
extra_css:
    - "css/custom.css"
