name: Build & Test
on:
  push:
  pull_request:
  schedule:
    - cron: '45 10 * * *'
jobs:
  test:
    name: Julia 1.12 - ubuntu-latest - x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.12'
          arch: x64
      - name: Run tests
        shell: julia --color=yes --project=test {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.update()
          using UnitCommitmentT
          try
            runtests()
          catch
            exit(1)
          end