name: Build & Test
on:
  push:
  pull_request:
  schedule:
    - cron: '45 10 * * *'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.6', '1.7', '1.8', '1.9']
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Run tests
        shell: julia --color=yes --project=test {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.update()
          using UnitCommitmentT
          try
            runtests()
          catch
            exit(1)
          end